#!/bin/bash

action=$1
version=$2

# add group and the user if they do not exit
if ! getent group [[serviceGroup]] >/dev/null; then
    addgroup --quiet \
             --system [[serviceGroup]]
fi

if ! getent passwd [[serviceUser]] >/dev/null; then
    adduser --quiet \
            --system \
            --ingroup [[serviceGroup]] \
            --no-create-home \
            --home /var/lib/[[artifactId]] \
            --shell /usr/sbin/nologin [[serviceUser]]
fi

exit 0
